/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/app_detection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/config`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/scan_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/breach_check/breach`; params?: Router.UnknownInputParams; } | { pathname: `/pages/breach_check/breach_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/device_health/device_health`; params?: Router.UnknownInputParams; } | { pathname: `/pages/phishing/phishing`; params?: Router.UnknownInputParams; } | { pathname: `/pages/phishing/scan_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/qr_scanner/qr_scanner`; params?: Router.UnknownInputParams; } | { pathname: `/pages/qr_scanner/scan_result`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/app_detection/app_detection`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/app_detection/config`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/app_detection/scan_result`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/breach_check/breach`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/breach_check/breach_result`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/device_health/device_health`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/phishing/phishing`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/phishing/scan_result`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/qr_scanner/qr_scanner`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/qr_scanner/scan_result`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/auth/sign-in${`?${string}` | `#${string}` | ''}` | `/auth/sign-up${`?${string}` | `#${string}` | ''}` | `/pages/app_detection/app_detection${`?${string}` | `#${string}` | ''}` | `/pages/app_detection/config${`?${string}` | `#${string}` | ''}` | `/pages/app_detection/scan_result${`?${string}` | `#${string}` | ''}` | `/pages/breach_check/breach${`?${string}` | `#${string}` | ''}` | `/pages/breach_check/breach_result${`?${string}` | `#${string}` | ''}` | `/pages/device_health/device_health${`?${string}` | `#${string}` | ''}` | `/pages/phishing/phishing${`?${string}` | `#${string}` | ''}` | `/pages/phishing/scan_result${`?${string}` | `#${string}` | ''}` | `/pages/qr_scanner/qr_scanner${`?${string}` | `#${string}` | ''}` | `/pages/qr_scanner/scan_result${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-in`; params?: Router.UnknownInputParams; } | { pathname: `/auth/sign-up`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/app_detection`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/config`; params?: Router.UnknownInputParams; } | { pathname: `/pages/app_detection/scan_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/breach_check/breach`; params?: Router.UnknownInputParams; } | { pathname: `/pages/breach_check/breach_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/device_health/device_health`; params?: Router.UnknownInputParams; } | { pathname: `/pages/phishing/phishing`; params?: Router.UnknownInputParams; } | { pathname: `/pages/phishing/scan_result`; params?: Router.UnknownInputParams; } | { pathname: `/pages/qr_scanner/qr_scanner`; params?: Router.UnknownInputParams; } | { pathname: `/pages/qr_scanner/scan_result`; params?: Router.UnknownInputParams; };
    }
  }
}
